apiVersion: pfe.rhpds.com/v1
kind: Gitea
metadata:
  name: gitea
  namespace: gitea
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  giteaSsl: true
  giteaAdminUser: gitea-admin
  giteaAdminPassword: "openshift"
  giteaAdminPasswordLength: 32
  giteaAdminEmail: gitea-admin@ignore-redhat.com
  giteaCreateUsers: true
  giteaGenerateUserFormat: "user1"
  giteaUserNumber: 1
  giteaUserPassword: openshift
  giteaMigrateRepositories: true
  giteaRepositoriesList:
  - repo: https://github.com/hamidreza2000us/coolstore.git
    name: coolstore
    private: false
  - repo: https://github.com/hamidreza2000us/inventory-quarkus.git
    name: inventory-quarkus
    private: false
  - repo: https://github.com/hamidreza2000us/web-nodejs.git
    name: web-nodejs
    private: false
  - repo: https://github.com/hamidreza2000us/catalog-spring-boot.git
    name: catalog-spring-boot
    private: false
  - repo: https://github.com/hamidreza2000us/gateway-vertx.git
    name: gateway-vertx
    private: false
