commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
  - github.com/redhat-cop/gitops-catalog///advanced-cluster-security-operator/operator/overlays/latest?ref=main?ref=main
  - github.com/redhat-cop/gitops-catalog///advanced-cluster-security-operator/instance/overlays/internal-registry-integration?ref=main?ref=main
  - init-acs.yaml

patches:
  - patch: |-
      - op: replace
        path: /spec/channel
        value: 'rhacs-4.1'
    target:
      kind: Subscription
      name: rhacs-operator
  - patch: |-
      - op: replace
        path: /spec/perNode/collector/collection
        value: EBPF
    target:
      kind: SecuredCluster